"""Skill manifest: the complete, portable skill description.

A manifest is everything a skill needs to be validated,
installed, executed and audited — without the registry:

- identity: skill_id, name, description, version, source
- contracts: input/output schemas
- requirements: tools, connectors, permissions, skill deps
- policy: risk level, execution limits, compatibility
- trust: verification status, integrity hash
- marketplace: category, author, quality signals
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from afnan_ai.redaction import redact_text


class SkillSource(str, Enum):
    """Where a skill came from — drives trust policy.

    SYSTEM — shipped with Afnan (highest trust).
    DEVELOPER — written by the developer (high trust).
    USER_CREATED — created by the user (medium trust).
    AGENT_GENERATED — generated by the agent (strict validation).
    IMPORTED — from an external package (untrusted until verified).
    """

    SYSTEM = "system"
    DEVELOPER = "developer"
    USER_CREATED = "user_created"
    AGENT_GENERATED = "agent_generated"
    IMPORTED = "imported"


# Source → default trust (0..1).  IMPORTED starts at 0 until
# the import pipeline verifies it.
SOURCE_TRUST = {
    SkillSource.SYSTEM: 1.0,
    SkillSource.DEVELOPER: 0.9,
    SkillSource.USER_CREATED: 0.7,
    SkillSource.AGENT_GENERATED: 0.4,
    SkillSource.IMPORTED: 0.0,
}


class VerificationStatus(str, Enum):
    UNVERIFIED = "unverified"
    SANDBOX_TESTED = "sandbox_tested"
    VERIFIED = "verified"


@dataclass
class ExecutionLimits:
    """Bounded execution: no unbounded loops or runaway skills."""

    max_steps: int = 50
    max_subskill_depth: int = 3
    timeout_s: float = 600.0
    max_loop_iterations: int = 100

    def __post_init__(self) -> None:
        self.max_steps = max(1, int(self.max_steps))
        self.max_subskill_depth = max(
            0, int(self.max_subskill_depth)
        )
        self.timeout_s = max(1.0, float(self.timeout_s))
        self.max_loop_iterations = max(
            1, int(self.max_loop_iterations)
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "max_steps": self.max_steps,
            "max_subskill_depth": self.max_subskill_depth,
            "timeout_s": self.timeout_s,
            "max_loop_iterations": self.max_loop_iterations,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ExecutionLimits":
        data = data or {}
        return cls(
            max_steps=int(data.get("max_steps", 50)),
            max_subskill_depth=int(
                data.get("max_subskill_depth", 3)
            ),
            timeout_s=float(data.get("timeout_s", 600.0)),
            max_loop_iterations=int(
                data.get("max_loop_iterations", 100)
            ),
        )


@dataclass
class SkillCompatibility:
    """What a skill needs from its host."""

    afnan_version: str = ""  # e.g. ">=1.2"
    os: tuple[str, ...] = ()  # windows|linux|macos, empty = any
    needs_browser: bool = False
    needs_computer: bool = False
    tool_versions: dict[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        self.os = tuple(
            o.lower() for o in (self.os or ())
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "afnan_version": self.afnan_version,
            "os": list(self.os),
            "needs_browser": self.needs_browser,
            "needs_computer": self.needs_computer,
            "tool_versions": dict(self.tool_versions),
        }

    @classmethod
    def from_dict(
        cls, data: dict[str, Any]
    ) -> "SkillCompatibility":
        data = data or {}
        return cls(
            afnan_version=str(data.get("afnan_version", "")),
            os=tuple(data.get("os") or ()),
            needs_browser=bool(data.get("needs_browser", False)),
            needs_computer=bool(
                data.get("needs_computer", False)
            ),
            tool_versions=dict(data.get("tool_versions") or {}),
        )


@dataclass
class SkillManifest:
    """The portable, signable skill description."""

    skill_id: str
    name: str
    description: str
    version: str = "1.0.0"
    source: SkillSource = SkillSource.DEVELOPER
    author: str = ""
    input_schema: dict[str, Any] = field(default_factory=dict)
    output_schema: dict[str, Any] = field(default_factory=dict)
    required_tools: tuple[str, ...] = ()
    required_connectors: tuple[str, ...] = ()
    required_permissions: tuple[str, ...] = ()
    skill_dependencies: tuple[str, ...] = ()
    risk_level: str = "read_only"
    capabilities: tuple[str, ...] = ()  # e.g. "network"
    limits: ExecutionLimits = field(
        default_factory=ExecutionLimits
    )
    compatibility: SkillCompatibility = field(
        default_factory=SkillCompatibility
    )
    verification_status: VerificationStatus = (
        VerificationStatus.UNVERIFIED
    )
    integrity_hash: str = ""
    category: str = ""
    tags: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        if isinstance(self.source, str):
            self.source = SkillSource(self.source)
        if isinstance(self.verification_status, str):
            self.verification_status = VerificationStatus(
                self.verification_status
            )
        self.required_tools = tuple(self.required_tools or ())
        self.required_connectors = tuple(
            self.required_connectors or ()
        )
        self.required_permissions = tuple(
            self.required_permissions or ()
        )
        self.skill_dependencies = tuple(
            self.skill_dependencies or ()
        )
        self.capabilities = tuple(self.capabilities or ())
        self.tags = tuple(self.tags or ())

    def trust_level(self) -> float:
        base = SOURCE_TRUST.get(self.source, 0.0)
        if self.source == SkillSource.IMPORTED and (
            self.verification_status
            == VerificationStatus.VERIFIED
        ):
            base = 0.6
        return base

    def to_dict(self) -> dict[str, Any]:
        return {
            "skill_id": self.skill_id,
            "name": redact_text(self.name)[:160],
            "description": redact_text(self.description)[:500],
            "version": self.version,
            "source": self.source.value,
            "author": redact_text(self.author)[:120],
            "input_schema": dict(self.input_schema),
            "output_schema": dict(self.output_schema),
            "required_tools": list(self.required_tools),
            "required_connectors": list(
                self.required_connectors
            ),
            "required_permissions": list(
                self.required_permissions
            ),
            "skill_dependencies": list(
                self.skill_dependencies
            ),
            "risk_level": self.risk_level,
            "capabilities": list(self.capabilities),
            "limits": self.limits.to_dict(),
            "compatibility": self.compatibility.to_dict(),
            "verification_status": (
                self.verification_status.value
            ),
            "integrity_hash": self.integrity_hash,
            "category": self.category,
            "tags": list(self.tags),
            "trust_level": self.trust_level(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "SkillManifest":
        data = data or {}
        return cls(
            skill_id=str(data.get("skill_id", "")),
            name=str(data.get("name", "")),
            description=str(data.get("description", "")),
            version=str(data.get("version", "1.0.0")),
            source=str(data.get("source", "developer")),
            author=str(data.get("author", "")),
            input_schema=dict(data.get("input_schema") or {}),
            output_schema=dict(data.get("output_schema") or {}),
            required_tools=tuple(
                data.get("required_tools") or ()
            ),
            required_connectors=tuple(
                data.get("required_connectors") or ()
            ),
            required_permissions=tuple(
                data.get("required_permissions") or ()
            ),
            skill_dependencies=tuple(
                data.get("skill_dependencies") or ()
            ),
            risk_level=str(
                data.get("risk_level", "read_only")
            ),
            capabilities=tuple(data.get("capabilities") or ()),
            limits=ExecutionLimits.from_dict(
                data.get("limits")
            ),
            compatibility=SkillCompatibility.from_dict(
                data.get("compatibility")
            ),
            verification_status=str(
                data.get("verification_status", "unverified")
            ),
            integrity_hash=str(
                data.get("integrity_hash", "")
            ),
            category=str(data.get("category", "")),
            tags=tuple(data.get("tags") or ()),
        )


def manifest_from_skill(skill: Any) -> SkillManifest:
    """Build a manifest from a Skill model instance."""
    deps = getattr(skill, "dependencies", None)
    return SkillManifest(
        skill_id=skill.skill_id,
        name=skill.name,
        description=skill.description,
        version=getattr(skill, "version", "1.0.0"),
        source=getattr(skill, "source", "developer"),
        author=getattr(skill, "created_by", ""),
        input_schema=dict(
            getattr(skill, "input_schema", None) or {}
        ),
        output_schema=dict(
            getattr(skill, "output_schema", None) or {}
        ),
        required_tools=tuple(
            getattr(deps, "tools", ()) or ()
        ),
        required_connectors=tuple(
            getattr(deps, "connectors", ()) or ()
        ),
        required_permissions=(),
        skill_dependencies=tuple(
            getattr(deps, "skills", ()) or ()
        ),
        risk_level=str(
            getattr(
                getattr(skill, "risk", ""), "value",
                getattr(skill, "risk", "read_only"),
            )
        ),
        capabilities=tuple(
            getattr(deps, "capabilities", ()) or ()
        ),
    )
